config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bootcamps do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy, :edit, :update, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bootcamp

  def total_price

    days = (end_date - start_date).to_i
    bootcamp.price * days

  end

end

app/models/bootcamp.rb
class Bootcamp < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings



  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_many_attached :photos

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bootcamps
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end
  #find(params[:id]) puxa pelo nome

  def new
    @bootcamp = Bootcamp.find(params[:bootcamp_id])
    @booking = Booking.new
  end

  def edit
  end

  def create
    @bootcamp = Bootcamp.find(params[:bootcamp_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.bootcamp = @bootcamp
    if @booking.save
      redirect_to booking_path(@booking)
    else
      puts @booking.errors.full_messages
      render :new
    end
  end

  def update

    if @booking.update(booking_params)
      redirect_to @booking, notice: 'booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
  @booking = Booking.find(params[:id])
  @booking.destroy
  redirect_to @booking.index
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/bootcamps_controller.rb
class BootcampsController < ApplicationController
  def index
    @bootcamps = Bootcamp.all
    @markers = @bootcamps.geocoded.map do |bootcamp|
      {
        lat: bootcamp.latitude,
        lng: bootcamp.longitude
      }
    end
  end

  def show
    @bootcamp = Bootcamp.find(params[:id])
    @markers = [
      {
        lat: @bootcamp.latitude,
        lng: @bootcamp.longitude
      }]
  end

  def new
    @bootcamp = Bootcamp.new
  end

  def edit
    @bootcamp = Bootcamp.find(params[:id])
  end

  def create
    @bootcamp = Bootcamp.new(bootcamp_params)
    @bootcamp.user = current_user
    if @bootcamp.save
      redirect_to @bootcamp
    else
      render :new
    end
  end

  def update
    @bootcamp = Bootcamp.find(params[:id])
    if @bootcamp.update(bootcamp_params)
      redirect_to @bootcamp, notice: 'Bootcamp was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bootcamp = Bootcamp.find(params[:id])
    @bootcamp.destroy
    redirect_to bootcamps_path
  end

  private

  def bootcamp_params
    params.require(:bootcamp).permit(:user_id, :address, :name, :pc_number, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h1>bookings</h1>

  <% @bookings.each do |booking| %>
    <%= link_to booking_path(booking) do %>
      <p class="booking-card"><%= booking.bootcamp.name %></p>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class='row vh-100 mt-5'  style='box-shadow: 1px 1px 3px #23c483; border-radius: 20px'>
    <div class='col-6 p-5 d-flex align-items-center' >
      <div class="w-100">
        <div class="d-flex  justify-content-between">
          <h1>Create a booking</h1>

          <%= link_to 'Return', bootcamps_path, class: "btn return-btn align-self-center" %>
        </div>

          <%= simple_form_for([@bootcamp, @booking]) do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit  class: 'btn btn-create btn-rounded m-3' %>
          <% end %>
          </div>
    </div>

    <div class='col-6' style="background-image: url('<%= image_path("booking.jpg")%>'); background-size: cover; background-position: center; border-radius: 0px 20px 20px 0px">

    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div>
  <h1><%= "the booking in #{@booking.bootcamp.name.capitalize}" %></h1>
  <p><%="for #{@booking.user.name}" %></p>
</div>

<ul>
<li>check-in at <%= l @booking.start_date, format: :long %></li>
<li>check-out at <%= l @booking.end_date, format: :long %></li>
<li>Total price: <%= number_to_currency(@booking.total_price) %>
</ul>

app/views/bootcamps/edit.html.erb
<div class="container">
  <div class='row vh-100 mt-5' style='box-shadow: 1px 1px 3px #23c483; border-radius: 20px'>
    <div class='col-6 p-5'>
      <div class="d-flex  justify-content-between">
        <h1>Editing Bootcamp</h1>

        <%= link_to 'Return', bootcamps_path, class: "btn return-btn align-self-center" %>
      </div>
      <div class="form-style">
        <%= simple_form_for (@bootcamp)  do |f|  %>
          <%= f.input :name  %>
          <%= f.input :address,

            input_html: { data: { geocoder_target: "address" }, class: "d-none" },
            wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }  %>

          <%= f.input :price %>
          <%= f.input :pc_number %>

          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-create btn-rounded'%>

          <%# <%= raise %>
       <% end %>
      </div>
    </div>

    <div class='col-6' style="background-image: url('<%= image_path("edit.jpg")%>');  background-size: cover; background-position: center; border-radius: 0px 20px 20px 0px">

    </div>
  </div>
</div>

app/views/bootcamps/index.html.erb
<div class="container mt-5 bootcamps ">
    <div>
    <div class="d-flex  justify-content-between">
      <h1>Bootcamps</h1>
      <%= link_to 'Create a bootcamp', new_bootcamp_path, class: 'btn btn-create' %>
    </div>

    <div class="card-display">
      <% @bootcamps.each do |bootcamp| %>
      <%= link_to bootcamp_path(bootcamp), class: "link-show" do %>

      <div class="card">
        <div class="blob"></div>
        <span class="img" style="background-image: url('<%=bootcamp.photos.attached? ? cl_image_path(bootcamp.photos.first.key) : asset_path("pcsetup.jpg")%>');  background-size: cover; background-position: center;"></span>
        <h2><%= bootcamp.name %><br><span><%= bootcamp.user.name %></span></h2>
        <p> start playing</p>
      </div>

      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/bootcamps/new.html.erb
<div class="container">
  <div class='row vh-100 mt-5'  style='box-shadow: 1px 1px 3px #23c483; border-radius: 20px'>
    <div class='col-6 p-5'>
      <div class="d-flex  justify-content-between">
        <h1>Create a bootcamp</h1>

        <%= link_to 'Return', bootcamps_path, class: "btn return-btn align-self-center" %>
      </div>
      <div class="form-style">
        <%= simple_form_for @bootcamp do |f|  %>
          <%= f.input :name  %>
          <%= f.input :address,

            input_html: { data: { geocoder_target: "address" }, class: "d-none" },
            wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }  %>

          <%= f.input :price %>
          <%= f.input :pc_number %>

          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-create btn-rounded'%>

          <%# <%= raise %>
        <% end %>
        </div>
    </div>

    <div class='col-6' style="background-image: url('<%= image_path("create.jpg")%>');  background-size: cover; background-position: center; border-radius: 0px 20px 20px 0px">

    </div>
  </div>
</div>

app/views/bootcamps/show.html.erb
<div class="px-5">

  <div class="d-flex justify-content-between align-items-center px-5 mx-5">
     <div class="d-flex align-items-center">
      <div>
        <h1><%= @bootcamp.name.capitalize %></h1>
        <p><%="by #{@bootcamp.user.name}" %></p>
      </div>
        <%= link_to 'Return', bootcamps_path, class: "mx-5 btn return-btn" %>
        </div>
      <div>
       <%= link_to 'Edit', edit_bootcamp_path(@bootcamp), class: 'btn btn-edit mx-5' %>
    <%= link_to 'X', bootcamp_path(@bootcamp), method: 'delete', data: { confirm: 'Remove bootcamp?' }, class: 'btn btn-delete' %>
      </div>
  </div>
  </div>
<div class="container">
  <div class="vh-100 row my-5 d-flex justify-content-between "  style='box-shadow: 1px 1px 3px #23c483; border-radius: 20px'>>
    <div class='col-3 p-5'>
      <% if @bootcamp.photos.attached? %>
        <% @bootcamp.photos.each do |photo| %>
          <div class="p-5" style="width:300px; height: 192px; background-image: url(<%= cl_image_path photo.key %>); background-size: cover; background-repeat: no-repeat;" >
            <div class="py-5">

            </div>
          </div>
        <% end %>
      <% else %>
        <div class="p-5" style="width:300px; height: 192px; background-image: url(<%= asset_path("pcsetup.jpg") %>); background-size: cover; background-repeat: no-repeat;" >
          <div class="py-5">

          </div>
        </div>
      <% end %>

    <ul class="mt-5 list-group">
    <li class="list-group-item" style="background-color:#1e2528; color:#d3d3d4"><strong>Address: </strong> <%="#{@bootcamp.address}" %></li>
    <li class="list-group-item" style="background-color:#1e2528; color:#d3d3d4"><strong>PC Number: </strong><%="#{@bootcamp.pc_number}" %></li>
    <li class="list-group-item" style="background-color:#1e2528; color:#d3d3d4"><%=  @bootcamp.availability ? "Available" : "Unavailable" %></li>
    <li class="list-group-item" style="background-color:#1e2528; color:#d3d3d4"><strong>Daily Price: </strong><%="#{@bootcamp.price}" %></li>

      <%= link_to 'Booking', new_bootcamp_booking_path(@bootcamp), class: 'btn btn-create btn-rounded mt-5' %>

    </ul>
  </div>
  <div class="col-1"></div>
  <div class='col-7 flex-grow-1' style=" background-size: cover; background-position: center; border-radius: 0px 20px 20px 0px"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaming House</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="vh-100">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%# <div class="main-container"> %>
      <%= yield %>
    <%# </div> %>

  </body>
      <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Developed by Júlio, Daniel and Shindy
      </div>
    </div>

</html>

app/views/pages/home.html.erb
  <div class="banner_home">
    <h1 class="gaming_house">Gaming House</h1>

    <div class="video" style="gradient-filter:(rgba(30, 30, 30, 0.5)0%, rgba(50, 50, 50, 0.3)40%)">
      <video playsinline muted autoplay loop>
        <source src="https://res.cloudinary.com/juliocb01/video/upload/v1654195205/eSports%20Bootcamps/pexels-yan-krukov-9071228_1_nf6cez.mp4" type="video/mp4">
      </video>
    </div>
  </div>
  <div class="my-5">
 <h3 class="message_below_video">Join with your team and prepare yourselves for the greatest challenge yet</h3>

<div class="d-flex justify-content-between mx-2">
    <div></div>
      <%= link_to "Start your journey now", bootcamps_path, class: "btn btn-create flex-end" %>
</div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Bootcamps", bootcamps_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://cdn.icon-icons.com/icons2/2200/PNG/512/gamer_avatar_icon_133991.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>